# fly.toml app configuration file generated for smc on 2023-06-13T16:05:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smc"
primary_region = "arn"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
